#!/usr/bin/env bash
#
# Build and run the personal-tools production image, optionally with an
# HTTPS-fronted nginx site + Let's Encrypt cert.
#
# On first run, asks whether you have a domain. If yes, prompts for the
# domain + admin email, saves them to .deploy-config, provisions a cert with
# certbot (standalone), installs the nginx site from nginx.conf, and reloads
# nginx. On subsequent runs, offers to reuse or change the saved domain.
#
#   ./deploy.sh              # interactive
#   PORT=3001 ./deploy.sh    # start from a different port
#   ./deploy.sh --yes        # never prompt (uses saved config; fails if port is busy)
#
set -euo pipefail

# Find the project root by walking up from this script until package.json turns
# up, so the script works whether it sits at the root or inside scripts/.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"
while [ ! -f "$PROJECT_ROOT/package.json" ] && [ "$PROJECT_ROOT" != "/" ]; do
  PROJECT_ROOT="$(dirname "$PROJECT_ROOT")"
done
if [ ! -f "$PROJECT_ROOT/package.json" ]; then
  echo "Could not find package.json at or above $SCRIPT_DIR" >&2
  exit 1
fi
cd "$PROJECT_ROOT"

IMAGE_NAME="personal-tools"
CONTAINER_NAME="personal-tools"
DEFAULT_PORT="${PORT:-3000}"
ASSUME_YES=false

CONFIG_FILE="$PROJECT_ROOT/.deploy-config"
NGINX_TEMPLATE="$PROJECT_ROOT/nginx.conf"
NGINX_SITE_NAME="personal-tools"
NGINX_AVAILABLE="/etc/nginx/sites-available/$NGINX_SITE_NAME"
NGINX_ENABLED="/etc/nginx/sites-enabled/$NGINX_SITE_NAME"

for arg in "$@"; do
  case "$arg" in
    -y|--yes) ASSUME_YES=true ;;
    -h|--help) sed -n '2,13p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "Unknown option: $arg" >&2; exit 1 ;;
  esac
done

# Prompts read from the terminal directly, so they still work when stdin is a pipe.
can_prompt() { [ "$ASSUME_YES" != true ] && [ -r /dev/tty ]; }

# --- env file -----------------------------------------------------------------

ENV_FILE=""
for candidate in .env.production .env.local .env; do
  if [ -f "$candidate" ]; then ENV_FILE="$candidate"; break; fi
done

if [ -z "$ENV_FILE" ]; then
  echo "No .env.production or .env.local found." >&2
  echo "Create one with MONGODB_URI, MONGODB_DB_NAME, APP_PASSWORD and SESSION_SECRET." >&2
  exit 1
fi

for required in MONGODB_URI APP_PASSWORD SESSION_SECRET; do
  if ! grep -q "^${required}=" "$ENV_FILE"; then
    echo "$ENV_FILE is missing $required" >&2
    exit 1
  fi
done

# --- saved config -------------------------------------------------------------

DOMAIN=""
ADMIN_EMAIL=""
if [ -f "$CONFIG_FILE" ]; then
  # shellcheck disable=SC1090
  . "$CONFIG_FILE"
fi

save_config() {
  umask 077
  cat > "$CONFIG_FILE" <<EOF
# Generated by deploy.sh — safe to edit or delete.
DOMAIN="${DOMAIN}"
ADMIN_EMAIL="${ADMIN_EMAIL}"
EOF
}

# --- domain prompt ------------------------------------------------------------

if [ -n "$DOMAIN" ]; then
  if can_prompt; then
    read -r -p "Use saved domain '$DOMAIN'? [Y/n] " reply < /dev/tty
    case "$reply" in
      [nN]*) DOMAIN=""; ADMIN_EMAIL="" ;;
    esac
  fi
fi

if [ -z "$DOMAIN" ]; then
  if can_prompt; then
    read -r -p "Do you have a domain to serve on? [y/N] " reply < /dev/tty
    case "$reply" in
      [yY]*)
        while [ -z "$DOMAIN" ]; do
          read -r -p "Enter your domain (e.g. example.com): " DOMAIN < /dev/tty
        done
        while [ -z "$ADMIN_EMAIL" ]; do
          read -r -p "Email for Let's Encrypt notices: " ADMIN_EMAIL < /dev/tty
        done
        save_config
        echo "Saved to $CONFIG_FILE (change any time by editing it or answering 'n' next run)."
        ;;
    esac
  fi
fi

# --- port selection -----------------------------------------------------------

port_in_use() {
  if command -v lsof >/dev/null 2>&1; then
    lsof -iTCP:"$1" -sTCP:LISTEN -n -P >/dev/null 2>&1
  elif command -v ss >/dev/null 2>&1; then
    ss -ltn "sport = :$1" 2>/dev/null | grep -q LISTEN
  else
    # No probe available — assume free and let `docker run` fail if it isn't.
    return 1
  fi
}

valid_port() {
  case "$1" in
    ''|*[!0-9]*) return 1 ;;
    *) [ "$1" -ge 1 ] && [ "$1" -le 65535 ] ;;
  esac
}

HOST_PORT="$DEFAULT_PORT"
while port_in_use "$HOST_PORT"; do
  echo "Port $HOST_PORT is already in use." >&2
  if ! can_prompt; then
    echo "Re-run with PORT=<free port> to pick another one." >&2
    exit 1
  fi
  read -r -p "Enter a different port (e.g. $((HOST_PORT + 1))): " HOST_PORT < /dev/tty
  if ! valid_port "$HOST_PORT"; then
    echo "'$HOST_PORT' is not a valid port number (1-65535)." >&2
    HOST_PORT="$DEFAULT_PORT"
  fi
done

# --- certbot (before build so a bad cert setup aborts early) ------------------

if [ -n "$DOMAIN" ]; then
  CERT_LIVE_DIR="/etc/letsencrypt/live/$DOMAIN"
  if [ ! -f "$CERT_LIVE_DIR/fullchain.pem" ]; then
    if ! command -v certbot >/dev/null 2>&1; then
      echo "certbot not found — install it (apt install certbot) and re-run." >&2
      exit 1
    fi
    echo "No cert found for $DOMAIN. Requesting one via certbot (standalone)..."
    sudo certbot certonly --standalone \
      --non-interactive --agree-tos \
      -m "$ADMIN_EMAIL" \
      -d "$DOMAIN" \
      --pre-hook 'systemctl stop nginx 2>/dev/null || true' \
      --post-hook 'systemctl start nginx 2>/dev/null || true'
  else
    echo "Reusing existing cert at $CERT_LIVE_DIR."
  fi
fi

# --- nginx site (also before build; reloading a broken nginx will fail here) --

if [ -n "$DOMAIN" ]; then
  if [ ! -f "$NGINX_TEMPLATE" ]; then
    echo "Missing nginx template at $NGINX_TEMPLATE" >&2
    exit 1
  fi
  if [ ! -d /etc/nginx/sites-available ] || [ ! -d /etc/nginx/sites-enabled ]; then
    echo "nginx sites-available/sites-enabled not found — is nginx installed?" >&2
    exit 1
  fi

  echo "Installing nginx site '$NGINX_SITE_NAME' for $DOMAIN -> 127.0.0.1:$HOST_PORT..."
  sed -e "s|__DOMAIN__|$DOMAIN|g" -e "s|__PORT__|$HOST_PORT|g" "$NGINX_TEMPLATE" \
    | sudo tee "$NGINX_AVAILABLE" > /dev/null
  sudo ln -sf "$NGINX_AVAILABLE" "$NGINX_ENABLED"

  sudo nginx -t
  sudo systemctl reload nginx
fi

# --- replace any previous container ------------------------------------------

if docker ps -a --format '{{.Names}}' | grep -qx "$CONTAINER_NAME"; then
  if can_prompt; then
    read -r -p "Container '$CONTAINER_NAME' already exists. Replace it? [y/N] " reply < /dev/tty
    case "$reply" in
      [yY]*) ;;
      *) echo "Aborted."; exit 1 ;;
    esac
  fi
  echo "Removing existing container '$CONTAINER_NAME'..."
  docker rm -f "$CONTAINER_NAME" >/dev/null
fi

# --- build and run ------------------------------------------------------------

echo "Building $IMAGE_NAME..."
docker build -t "$IMAGE_NAME" .

echo "Starting $CONTAINER_NAME on port $HOST_PORT (env: $ENV_FILE)..."
docker run -d \
  --name "$CONTAINER_NAME" \
  --env-file "$ENV_FILE" \
  --restart unless-stopped \
  -p "${HOST_PORT}:3000" \
  "$IMAGE_NAME"

echo
if [ -n "$DOMAIN" ]; then
  echo "App running at https://$DOMAIN (via nginx) and http://localhost:${HOST_PORT} (direct)"
else
  echo "App running at http://localhost:${HOST_PORT}"
fi
echo "Logs:  docker logs -f $CONTAINER_NAME"
echo "Stop:  docker stop $CONTAINER_NAME"
